# Generated by Django 5.1.1 on 2026-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='diameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbital_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='rotation_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='surface_water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
