# Generated by Django 5.1.1 on 2026-02-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0002_alter_planet_climate_alter_planet_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='homeworld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ex09.planet'),
        ),
    ]
