# Generated by Django 5.1.1 on 2026-02-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('eye_color', models.CharField(max_length=255)),
                ('hair_color', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('mass', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.CharField(max_length=255)),
                ('diameter', models.IntegerField()),
                ('orbital_period', models.IntegerField()),
                ('rotation_period', models.IntegerField()),
                ('surface_water', models.FloatField()),
                ('population', models.BigIntegerField()),
                ('terrain', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('episode_nb', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=64)),
                ('producer', models.CharField(max_length=128)),
                ('release_date', models.DateField()),
                ('charecters', models.ManyToManyField(related_name='movies', to='ex10.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='homeworld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex10.planet'),
        ),
    ]
