# Generated by Django 5.1.1 on 2026-02-23 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='charecters',
            new_name='characters',
        ),
        migrations.AlterField(
            model_name='movies',
            name='opening_crawl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='eye_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hair_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='homeworld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ex10.planet'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='climate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='diameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbital_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='rotation_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='surface_water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
