# Generated by Django 5.1.1 on 2026-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0002_rename_charecters_movies_characters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='episode_nb',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
